### PR TITLE
builder/source/simple: Disable compression when downloading artifacts

### LINKED ISSUE #989: homebank: Unable to fetch the tarball in solbuild
### Summary

Although there is no problem when running the update command locally to update the source, this error appears when the build command is given in solbuild.

homebank

### Steps to reproduce

go to homebank dir and run `task build` or `go-task build`

### Expected result

A successful build.

### Actual result

`Error downloading http://homebank.free.fr/public/sources/homebank-5.7.2.tar.gz: bad content length`

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

OS: Solus x86_64 
Host: CELSIUS W530 
Kernel: 6.6.4-265.current 
Shell: bash 5.1.16 
DE: Budgie 10.8.2 
WM: Mutter(Budgie) 
Terminal: gnome-terminal 
CPU: Intel Xeon E3-1271 v3 (8) @ 4.000GHz 
GPU: NVIDIA Quadro M2000 
Memory: 3122MiB / 15920MiB 

### Other comments

To update this package a workaround for now would be by hosting the tarball in our sources repo.

### PR DESCRIPTION
**Pull request by joebonrichie**
Generally causing more issues than it solves. It's usefulness is also pretty debatable when we're downloading pre-compressed artifacts.

Resolves https://github.com/getsolus/packages/issues/989.

### CODE REVIEW

**Comment by ermo** [comment]
It looks simple and straightforward, but I'd be inclined to hear Silke's opinion as well.

File: builder/source/simple.go [hunk 1]
```diff
@@ -137,7 +138,17 @@ func (s *SimpleSource) download(destination string) error {
...
-	resp := grab.NewClient().Do(req)
+	// Keep go-grab defaults but also disable compression
+	// https://github.com/cavaliergopher/grab/blob/v3.0.1/v3/client.go#L53
+	tr := &http.Transport{
+		DisableCompression: true,
+		Proxy:              http.ProxyFromEnvironment,
+	}
+
+	client := grab.NewClient()
+	client.HTTPClient = &http.Client{Transport: tr}
```
Comment (silkeh) [inline builder/source/simple.go]: Why not go all the way? Seems the only thing we're keeping by using `NewClient` is the user agent:

```suggestion
	// Create a client with compression disabled.
	// See: https://github.com/cavaliergopher/grab/blob/v3.0.1/v3/client.go#L53
	client := &grab.Client{
		UserAgent: "solbuild",
		HTTPClient: &http.Client{
			Transport: &http.Transport{
				DisableCompression: true,
				Proxy:              http.ProxyFromEnvironment,
			}
		}
	}
```

**Review by silkeh — APPROVED** [review]
LGTM, thanks!
